### ISSUE TITLE
extended Task2

### ISSUE THREAD

**Issue by arghyakusumdas** [arghyakusumdas/TurtleFox#10]
I could not find your extended task2 (Specifically the analysis in the MS Word).
Please see me after class.
I think there is a problem in your Github submission.
Please show me the file that I should grade in your GitHub commit.

I am giving a 0 for now. but don't worry. I Will fix it when you will show me the correct file.

**Comment by schultzder** [comment]
The analysis for task 2 extended is appended to the word document we used for task 2. The documents file name is "Task2_WordDoc_V1.2". The MS Project file also includes additional information in the resource sheet. The Project file also has new tasks in the gantt chat view.  Sorry for not making a separate document.
