### ISSUE TITLE
Project Issues task2

### ISSUE THREAD

**Issue by arghyakusumdas** [arghyakusumdas/TurtleFox#8]
1) Since you are hiring employees, add a separate task called 'hiring employees' for that. Add at least one subtask task called 'interviewing new employees' under that task. Then adjust the schedule accordingly.
2) Add the time of your analysis as a subtask under online survey and registration

**Comment by Kielerca** [comment]
1. Added a Task called "hiring employees" at the before all other tasks, we decided to hire employees in August before diving into the rest of the project and before moving forward. We also added a sub task for interviewing all 5 employees ( 1 hour for each employee)
2. Added a subtask of Feasability analysis under online survey and registration
