### ISSUE TITLE
Visio issues task2

### ISSUE THREAD

**Issue by arghyakusumdas** [arghyakusumdas/TurtleFox#9]
1) Always remember that your level 0 and context diagram should have exactly same arrows coming in and going out from an external entity.
For example, in the level 0 diagram, the student entity has incoming arrows named 'receive grade exam to take'. They are missing in your context diagram. This is only one example. There are several other.
Rectify all these issues 
This is a very serious problem in DFD
2) External entity (University management) cannot connect to data store (student database) directly

**Comment by Jubbernaut99** [comment]
I fixed the main issues, I just have to add some data bases. I plan on doing it Monday, tomorrow, night in the lab
